  .
  .
  .
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "microservice.name" . }}
          topologyKey: "kubernetes.io/hostname"
  .
  .
  .